
name: tv_legal_app
description: App de TV pública com canais ao vivo, feedback e mapa.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chewie: ^1.7.0
  better_player: ^0.0.83
  video_player: ^2.7.0
  google_maps_flutter: ^2.6.0
  google_mobile_ads: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/